export const descriptions = {
  '!': 'Exclamation mark',
  $: 'Dollar sign',
  '(': 'Left paren',
  ')': 'Right paren',
  ':': 'Mid-sent punctuation',
  ',': 'Comma',
  ';': 'Semicolon',
  '.': 'Sent-final punctuation',
  '#': 'Pound sign',
  '``': 'Quote',
  SYM: 'Symbol',
  CC: 'Coordinating conjunction',
  DT: 'Determiner',
  EX: 'Existential there',
  FW: 'Foreign Word',
  IN: 'Preposition',
  JJ: 'Adjective',
  JJS: 'Adjective, superlative',
  JJR: 'Adjective, comparative',
  LS: 'List item marker',
  MD: 'Modal',
  NN: 'Noun, singular or mass',
  NNS: 'Noun, plural',
  NNP: 'Proper Noun, singular',
  NNPS: 'Proper noun, plural',
  PDT: 'Predeterminer',
  POS: 'Possessive ending',
  PRP: 'Personal pronoun',
  PRP$: 'Possessive pronoun',
  RB: 'Adverb',
  RBS: 'Adverb, superlative',
  RBR: 'Adverb, comparative',
  RP: 'Particle',
  TO: '"to"',
  UH: 'Interjection',
  VB: 'Verb, base form',
  VBD: 'Verb, past tense',
  VBG: 'Verb, present participle/gerund',
  VBN: 'Verb, past participle',
  VBP: 'Verb, non 3rd person, singular, present',
  VBZ: 'Verb, 3rd singular present',
  WDT: 'Wh-determiner',
  WRB: 'Wh-adverb',
  WP: 'Wh-pronoun',
  WP$: 'Possessive-Wh'
}
